enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  WELCOME_SCREEN="WELCOME_SCREEN",
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN="SIGNUP_SCREEN",
  FORGOT_PASSWORD="FORGOT_PASSWORD",
  CREATE_PASSWORD="CREATE_PASSWORD",
  LocationAccessScreen='LocationAccessScreen',
  LocationPicker='LocationPicker',
  MyBookings='MyBookings',
  Reward='Reward',
  PaymentMethods='PaymentMethods',
  LoginOption='LoginOption',
  COMPANYHOME_SCREEN='COMPANYHOME_SCREEN',
  JobDetailsScreen='JobDetailsScreen',
  NotificationScreen='NotificationScreen',
  COMPANYPROFILE_SCREEN='COMPANYPROFILE_SCREEN',
  ProfileScreen='ProfileScreen',
  NotificationSetting='NotificationSetting',
  SupportScreen='SupportScreen',
  Aboutus='Aboutus',

  OTP_SCREEN = 'OTP_SCREEN',
  PROFILE_DETAILS = 'PROFILE_DETAILS',
  HOME_SCREEN = "HOME_SCREEN",
  BOTTAM_TAB = 'BOTTAM_TAB',
  ALL_SERVICES = 'ALL_SERVICES',
  BIKE_DETAILS = "BIKE_DETAILS",
  NEARBY_SHOPS = "NEARBY_SHOPS",
  GARAGE_DETAILS = "GARAGE_DETAILS",
  BOOKING_COMPLETE = "BOOKING_COMPLETE",
  BOOKING_SCREEN = 'BOOKING_SCREEN',
  SUPPORT_SCREEN = "SUPPORT_SCREEN",
  REWARD_SCREEN = 'REWARD_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SERVICE_SUMMERY = 'SERVICE_SUMMERY',
  EDIT_PROFILE = 'EDIT_PROFILE',
  BookingDetails='BookingDetails',
  ManageAddress='ManageAddress',
  Wallet='Wallet',
  CHANGE_PASSWORD='CHANGE_PASSWORD',
  COMPANY_LOGIN='COMPANY_LOGIN',
 
  VEHICAL_SCREEN = 'VEHICAL_SCREEN',
  NOTIFICATION_SETTING ="NOTIFICATION_SETTING",
  ABOUT_SCREEN ="ABOUT_SCREEN",
  PRIVACY_POLICY='PRIVACY_POLICY',
  CarBodyTypeScreen='CarBodyTypeScreen',
  AddVehicleScreen='AddVehicleScreen',
  CarList='CarList',
  BookServiceScreen='BookServiceScreen',
  PickUpAddress='PickUpAddress',
  PaymentMethod='PaymentMethod',
  PaymentSummary='PaymentSummary',
  Congratulation='Congratulation',
  FilterScreen='FilterScreen',
  EXPLORE_SCREEN='EXPLORE_SCREEN',
  BOOKMARK_SCREEN ="BOOKMARK_SCREEN",
  CHAT_SCREEN='CHAT_SCREEN',
  ChatScreen='ChatScreen',
  PriceGuide='PriceGuide',
  BookingList='BookingList',
  LeaveReview='LeaveReview',
  HelpCenter='HelpCenter'


}

export default ScreenNameEnum;
